-- AURORA menu: 10 ta noyob taom (har biri alohida rasm URL).
-- Takroriy qatorlarni tozalash uchun: supabase/seed/reset_and_seed_menu.sql faylini ishga tushiring.

insert into public.menu_items (
  name_uz,
  name_en,
  name_ru,
  description_uz,
  description_en,
  description_ru,
  price,
  category,
  image_url,
  tags,
  ingredients_uz,
  ingredients_en,
  ingredients_ru
) values
(
  'Qora trufel arancini',
  'Black Truffle Arancini',
  'Аранчини с чёрным трюфелем',
  'Xrustlay qobiq, mozzarella yadro va trufel mayonezi bilan issiq ris sharlari.',
  'Crisp risotto spheres with molten mozzarella and black truffle aioli.',
  'Хрустящие шарики из ризотто с тёплой моцареллой и соусом из чёрного трюфеля.',
  24.00,
  'starters',
  'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80',
  array['Vegetarian'],
  array['ris', 'mozzarella', 'qora trufel', 'panko', 'sariyog'''],
  array['arborio rice', 'mozzarella', 'black truffle', 'panko', 'butter'],
  array['рис арборio', 'моцарелла', 'чёрный трюфель', 'панко', 'сливочное масло']
),
(
  'Mol go''shti tartar',
  'Wagyu Beef Tartare',
  'Тартар из мраморной говядины',
  'Yengil wasabi kremi, tuxum sariq va qizil piyoz bilan nozik go''sht.',
  'Hand-cut wagyu with wasabi cream, quail yolk, and pickled shallot.',
  'Ручная нарезка wagyu с кремом васаби, перепелиным желтком и луком-шалот.',
  32.00,
  'starters',
  'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
  array['Halal', 'Gluten-Free'],
  array['wagyu go''sht', 'wasabi', 'tuxum sariq', 'kapari', 'zaytun moyi'],
  array['wagyu beef', 'wasabi', 'quail egg', 'capers', 'olive oil'],
  array['говядина wagyu', 'васаби', 'перепелиное яйцо', 'каперсы', 'оливковое масло']
),
(
  'Burrata va qora balsamik',
  'Burrata & Aged Balsamic',
  'Буррата с выдержанным бalsamico',
  'Yangi pomidor, basilik va 18 yillik balsamik sirka ostida yumshoq burrata.',
  'Creamy burrata over heirloom tomatoes, basil oil, and 18-year balsamic.',
  'Нежная burrata на томатах, масло базилика и бalsamico 18-летней выдержки.',
  22.00,
  'starters',
  'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800&q=80',
  array['Vegetarian', 'Gluten-Free'],
  array['burrata', 'pomidor', 'basilik', 'balsamik', 'tuz'],
  array['burrata', 'tomatoes', 'basil', 'balsamic', 'sea salt'],
  array['burrata', 'томаты', 'базилик', 'бalsamico', 'морская соль']
),
(
  'Cho''zilgan okean somoni',
  'Pan-Seared Atlantic Salmon',
  'Лосось с хрустящей кожей',
  'Yashil sparja, limon-dill sousi va qizil ikra bilan.',
  'Crisp skin salmon, charred asparagus, lemon-dill beurre blanc, salmon roe.',
  'Лосось с хрустящей кожей, спаржа, соус бёль блан с укропом и икрой.',
  48.00,
  'mains',
  'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
  array['Gluten-Free'],
  array['somon', 'sparja', 'sariyog''', 'limon', 'dill'],
  array['salmon', 'asparagus', 'butter', 'lemon', 'dill'],
  array['лосось', 'спаржа', 'сливочное масло', 'лимон', 'укроп']
),
(
  'Qora risotto',
  'Squid Ink Risotto',
  'Ризотто с чернилами кальмара',
  'Qizg''on shrimps, parmesan va limon zest bilan chuqur qora risotto.',
  'Silky squid ink risotto with prawns, parmesan, and preserved lemon.',
  'Шёлковистое ризотто с чернилами кальмара, креветками и пармезаном.',
  42.00,
  'mains',
  'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
  array['Halal'],
  array['ris', 'kalmar miyasi', 'shrimps', 'parmesan', 'limon'],
  array['arborio rice', 'squid ink', 'prawns', 'parmesan', 'lemon'],
  array['рис', 'чернила кальмара', 'креветки', 'пармезан', 'лимон']
),
(
  'AURORA Wagyu ribeye',
  'AURORA Wagyu Ribeye',
  'Рибай Wagyu AURORA',
  '300 g marbled ribeye, qizil vino sousi va trufel kartoshka bilan.',
  '300 g marbled ribeye, red wine jus, and truffle potato purée.',
  '300 г рибай wagyu, соус из красного вина и пюре из картофеля с трюфелем.',
  98.00,
  'steaks',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  array['Halal', 'Gluten-Free'],
  array['wagyu ribeye', 'qizil vino', 'trufel', 'kartoshka', 'tuz'],
  array['wagyu ribeye', 'red wine', 'truffle', 'potato', 'sea salt'],
  array['рибай wagyu', 'красное вино', 'трюфель', 'картофель', 'морская соль']
),
(
  'Quruq eskirgan tomahawk',
  'Dry-Aged Tomahawk',
  'Томагавк длительной выдержки',
  '45 kunlik dry-aged, 900 g, chimichurri va qovurilgan sarimsoq bilan.',
  '45-day dry-aged 900 g tomahawk, chimichurri, and roasted garlic.',
  'Томагавк 900 г с выдержкой 45 дней, chimichurri и запечённый чеснок.',
  145.00,
  'steaks',
  'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
  array['Halal'],
  array['tomahawk', 'sarimsoq', 'maydanoz', 'zaytun moyi', 'tuz'],
  array['tomahawk steak', 'garlic', 'parsley', 'olive oil', 'sea salt'],
  array['стейк томагавк', 'чеснок', 'петрушка', 'оливковое масло', 'морская соль']
),
(
  'File mignon',
  'Filet Mignon',
  'Филе-миньон',
  '250 g nozik file, qora shokolad-murch sousi va baby sabzavotlar.',
  '250 g tender filet, black pepper-cocoa jus, and glazed baby vegetables.',
  '250 г нежного филе, перечно-шоколадный jus и глазированные овощи.',
  86.00,
  'steaks',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  array['Halal', 'Gluten-Free'],
  array['file mignon', 'qora murch', 'shokolad', 'sabzavot', 'sariyog'''],
  array['filet mignon', 'black pepper', 'cocoa', 'vegetables', 'butter'],
  array['филе-миньон', 'чёрный перец', 'какао', 'овощи', 'сливочное масло']
),
(
  'Qora shokolad sufle',
  'Dark Chocolate Soufflé',
  'Суфле из тёмного шоколада',
  'Issiq sufle, 70% Valrhona va vanil mus bilan.',
  'Warm 70% Valrhona soufflé with vanilla bean crème anglaise.',
  'Тёплое суфле из Valrhona 70% с ванильным crème anglaise.',
  18.00,
  'desserts',
  'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80',
  array['Vegetarian', 'Gluten-Free'],
  array['qora shokolad', 'tuxum', 'shakar', 'vanil', 'sut'],
  array['dark chocolate', 'eggs', 'sugar', 'vanilla', 'cream'],
  array['тёмный шоколад', 'яйца', 'сахар', 'ваниль', 'сливки']
),
(
  'AURORA espresso martini',
  'AURORA Espresso Martini',
  'Эспрессо-мартини AURORA',
  'Double espresso, vanil vodka va qora kakao kremasi.',
  'Double espresso, vanilla vodka, coffee liqueur, and cocoa foam.',
  'Двойной эспрессо, ванильная водка, кофейный ликёр и какао-пена.',
  16.00,
  'drinks',
  'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
  array['Vegan', 'Gluten-Free'],
  array['espresso', 'vodka', 'kofe likyori', 'kakao'],
  array['espresso', 'vodka', 'coffee liqueur', 'cocoa'],
  array['эспрессо', 'водка', 'кофейный ликёр', 'какао']
);
